### ISSUE TITLE
Multi-Thread task hangs up.

### ISSUE THREAD

**Issue by zekungao** [ICBench/OpenSTA#5]
Some testcase while repeating the STA calculations, met a problem that the multi-thread task hangs up.
The procedure didn't crash and can be terminated immediately.

The `pstack` show the final mirror is as:
```shell
Thread 1 (process 60192):
#0  0x00007f3c01a6071b in ?? ()
#1  0x0000556e3a7aae65 in sta::DispatchQueue::finishTasks() ()
...
```

We guess the mutex lock in multi-thread pool has some problem.

**Comment by zekungao** [comment]
The hack way to avoid this problem is to use following cmd to forced it to use only 1 thread

```tcl
set_thread_count 1
```

But it may makes the STA calculation slower.
